merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=main
      - or:
          - "#approved-reviews-by>=1"
          - author=jacobweinstock
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - check-success=DCO
      - check-success~=^Prepare .*
      - check-success~=^LinuxKit .*
      - check-success~=^Hook .*
      - check-success~=^Kernel .*
      - label!=do-not-merge
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - base=main
      - or:
          - "#approved-reviews-by>=1"
          - author=jacobweinstock
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - check-success=DCO
      - check-success~=^Prepare .*
      - check-success~=^LinuxKit .*
      - check-success~=^Hook .*
      - check-success~=^Kernel .*
      - label!=do-not-merge
      - label=ready-to-merge
      # This extra condition forces draft PR mode (prevents in-place checks)
      - queue-position>=0
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: merge

pull_request_rules:
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
