# a 'peg' is not a 'hook', instead, just a bare LinuxKit image. It does use Hook's kernel though.
# this exists so we can experiment with newer LK versions and the dind interaction.
# EXCLUSIVELY for development, this should never be released.
kernel:
  image: "${HOOK_KERNEL_IMAGE}"
  cmdline: irrelevant=here
  #ucode: intel-ucode.cpio
init:
  - linuxkit/init:45a1ad5919f0b6acf0f0cf730e9434abfae11fe6
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:e7a92d9f3282039eac5fb1b07cac2b8664cbf0ad
  #- linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
  #- linuxkit/firmware:8def159583422181ddee3704f7024ecb9c02d348
onboot:
  - name: rngd1
    image: linuxkit/rngd:cdb919e4aee49fed0bf6075f0a104037cba83c39
    command: [ "/sbin/rngd", "-1" ]
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
  - name: modprobe
    image: linuxkit/modprobe:ab5ac4d5e7e7a5f2d103764850f7846b69230676
    command: [ "modprobe", "cdc_ncm" ] # for usb ethernet dongles
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: [ "/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1" ]
services:
  #- name: rngd
  #  image: linuxkit/rngd:cdb919e4aee49fed0bf6075f0a104037cba83c39
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    capabilities:
      - all
    binds.add:
      - /:/host2
    env:
      - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:75f399fbfb6455dfccd4cb30543d0b4b494d28c8
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true